# Generated by Django 4.2.30 on 2026-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdblistrr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarrinstance',
            name='minimum_availability',
            field=models.CharField(choices=[('announced', 'Announced'), ('inCinemas', 'In Cinemas'), ('released', 'Released'), ('preDB', 'PreDB')], default='released', max_length=20),
        ),
    ]
