# Generated by Django 6.0.8 on 2026-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdblistrr', '0002_radarrinstance_minimum_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarrinstance',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sonarrinstance',
            name='monitor',
            field=models.CharField(choices=[('all', 'All Episodes'), ('future', 'Future Episodes'), ('missing', 'Missing Episodes'), ('existing', 'Existing Episodes'), ('recent', 'Recent Episodes'), ('pilot', 'Pilot Episode'), ('firstSeason', 'First Season'), ('latestSeason', 'Latest Season'), ('none', 'None')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='sonarrinstance',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
