# Generated by Django 6.0.8 on 2026-08-17 13:08

import mdblistrr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdblistrr', '0003_radarr_sonarr_tags_and_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='value',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='radarrinstance',
            name='apikey',
            field=mdblistrr.models.EncryptedCharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='sonarrinstance',
            name='apikey',
            field=mdblistrr.models.EncryptedCharField(max_length=2048),
        ),
    ]
