# Generated by Django 6.0.8 on 2026-08-22 11:40

import django.db.models.deletion
import mdblistrr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdblistrr', '0004_secure_secret_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlexInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('token', mdblistrr.models.EncryptedCharField(max_length=2048)),
                ('server_client_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('library_ids', models.CharField(blank=True, default='', max_length=500)),
                ('badge_score_enabled', models.BooleanField(default=True)),
                ('badge_age_rating_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlexPosterState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating_key', models.CharField(max_length=50)),
                ('section_id', models.CharField(blank=True, default='', max_length=50)),
                ('section_type', models.CharField(blank=True, default='', max_length=10)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tvdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('stamped_score', models.IntegerField(blank=True, null=True)),
                ('stamped_age_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('last_thumb_key', models.CharField(blank=True, default='', max_length=255)),
                ('last_uploaded_thumb_key', models.CharField(blank=True, default='', max_length=255)),
                ('original_poster_cache_path', models.CharField(blank=True, default='', max_length=500)),
                ('mdblist_checked_at', models.DateTimeField(blank=True, null=True)),
                ('stamped_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plex_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_states', to='mdblistrr.plexinstance')),
            ],
            options={
                'indexes': [models.Index(fields=['plex_instance', 'imdb_id'], name='idx_plex_poster_imdb')],
                'constraints': [models.UniqueConstraint(fields=('plex_instance', 'rating_key'), name='uniq_plex_poster_state')],
            },
        ),
    ]
