# Generated by Django 6.0.8 on 2026-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdblistrr', '0005_plexinstance_plexposterstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlexSyncRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='running', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('stamped', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('current_title', models.CharField(blank=True, default='', max_length=255)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
