# Generated by Django 6.0.8 on 2026-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdblistrr', '0006_plexsyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='plexinstance',
            name='sync_audience_rating_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plexposterstate',
            name='original_audience_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plexposterstate',
            name='synced_audience_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plexsyncrun',
            name='kind',
            field=models.CharField(choices=[('sync', 'Sync'), ('reset', 'Reset to original')], default='sync', max_length=10),
        ),
    ]
