# Generated by Django 6.0.8 on 2026-08-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdblistrr', '0007_plexinstance_sync_audience_rating_enabled_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plexsyncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='uniq_plexsyncrun_running'),
        ),
    ]
